"""Produce the source-code listing submitted with a software registration.

    python tools/make_listing.py                     # the whole program
    python tools/make_listing.py --lines-per-page 40
    python tools/make_listing.py --first-last 25     # first 25 + last 25 pages

The registration asks for "identifying material" -- a printed listing of the
source. What counts as the program is `smartroad/` plus `app.py`: the ASTM
engine, the geometry, the detector wrapper and the interface. Training scripts,
tooling and tests are auxiliary and are left out unless --everything is passed.

`smartroad/pci/curves.py` is excluded always. It is generated by
tools/gen_curves.py from the MIT-licensed brandnewbox/pavement_condition_index,
which digitised ASTM's printed curves. Those coefficients are not ours to claim.
"""
from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

#: The program proper, in reading order -- engine first, interface last.
PROGRAM = (
    "smartroad/__init__.py",
    "smartroad/pci/__init__.py",
    "smartroad/pci/astm.py",
    "smartroad/pci/engine.py",
    "smartroad/pci/from_detections.py",
    "smartroad/pci/from_survey.py",
    "smartroad/geometry/__init__.py",
    "smartroad/geometry/ipm.py",
    "smartroad/detect/__init__.py",
    "smartroad/detect/tiled.py",
    "smartroad/survey/__init__.py",
    "smartroad/survey/video.py",
    "smartroad/report/__init__.py",
    "smartroad/report/parse_results.py",
    "smartroad/report/build_report.py",
    "smartroad/data/__init__.py",
    "smartroad/data/build_yolo.py",
    "app.py",
)

AUXILIARY = (
    "tools/gen_curves.py",
    "tools/kaggle_fetch.py",
    "scripts/download_models.py",
    "bin/dashboard.py",
    "kaggle/train_detector.py",
    "kaggle/run.py",
    "vast/train_detector.py",
    "vast/train.py",
    "vast/train_remote.py",
)

TITLE = "Smart Road — ASTM D6433 bo'yicha yo'l qoplamasi holati indeksini hisoblovchi dastur"
AUTHORS = ("Abdurakhmonov Dostonbek", "Soataliyev Raximjon")


def paginate(lines: list[str], per_page: int) -> list[list[str]]:
    return [lines[i:i + per_page] for i in range(0, len(lines), per_page)]


def build(files: tuple[str, ...]) -> tuple[list[str], int]:
    """Return numbered listing lines, and the count of real source lines."""
    out: list[str] = []
    source_lines = 0
    for rel in files:
        path = ROOT / rel
        if not path.exists():
            out.append(f"!!! TOPILMADI: {rel}")
            continue
        body = path.read_text(encoding="utf-8").splitlines()
        source_lines += len(body)
        out.append("")
        out.append("=" * 78)
        out.append(f"FAYL: {rel}    ({len(body)} satr)")
        out.append("=" * 78)
        # Per-file numbering: a reviewer checks a file against the repository,
        # not against a running total across the whole document.
        out.extend(f"{n:5d}  {line}" for n, line in enumerate(body, 1))
    return out, source_lines


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lines-per-page", type=int, default=50)
    ap.add_argument("--first-last", type=int, metavar="N",
                    help="keep only the first N and last N pages")
    ap.add_argument("--everything", action="store_true",
                    help="include the auxiliary scripts as well")
    ap.add_argument("-o", "--out", default="DASTUR_KODI.txt")
    args = ap.parse_args()

    files = PROGRAM + (AUXILIARY if args.everything else ())
    listing, source_lines = build(files)
    pages = paginate(listing, args.lines_per_page)
    total_pages = len(pages)

    kept = pages
    note = ""
    if args.first_last and total_pages > 2 * args.first_last:
        kept = pages[:args.first_last] + pages[-args.first_last:]
        note = (f"Ushbu nusxada {total_pages} betdan birinchi {args.first_last} va "
                f"oxirgi {args.first_last} beti keltirilgan.")

    head = [
        "=" * 78,
        "EHM UCHUN DASTURNI IDENTIFIKATSIYA QILUVCHI MATERIALLAR DASTLABKI MATNI",
        "(DASTUR KODI)",
        "=" * 78,
        "",
        f"Dastur nomi:      {TITLE}",
        f"Mualliflar:       {', '.join(AUTHORS)}",
        f"Dasturlash tili:  Python 3.12+",
        f"Manba:            https://github.com/uzbtrust/smart-road",
        f"Sana:             {dt.date.today().isoformat()}",
        "",
        f"Fayllar soni:     {len(files)}",
        f"Kod hajmi:        {source_lines} satr",
        f"Betlar soni:      {total_pages}  ({args.lines_per_page} satr/bet)",
    ]
    if note:
        head.append("")
        head.append(note)
    head += [
        "",
        "IZOH: smartroad/pci/curves.py fayli ushbu listingga kiritilmagan.",
        "U tools/gen_curves.py orqali MIT litsenziyali begona manbadan",
        "(brandnewbox/pavement_condition_index) avtomatik generatsiya qilinadi",
        "va mualliflik da'vosi ob'ekti emas.",
        "",
        "=" * 78,
    ]

    body: list[str] = []
    for i, page in enumerate(kept, 1):
        body.extend(page)
        body.append("")
        body.append(f"{'— ' + str(i) + ' —':^78}")
        body.append("\f")

    target = ROOT / args.out
    target.write_text("\n".join(head + body), encoding="utf-8")
    print(f"{target.relative_to(ROOT)}  —  {len(files)} fayl, {source_lines} satr, "
          f"{len(kept)} bet")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
